require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  EnabledByDefault: true
  Exclude:
    - '**/test.rb'
  TargetRubyVersion: 3.0.3

Bundler/GemComment:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Gemspec/DependencyVersion:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument
  IndentationWidth: 4

Layout/EmptyLineAfterMultilineCondition:
  Enabled: false

Layout/FirstArgumentIndentation:
  IndentationWidth: 4

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/FirstMethodParameterLineBreak:
  Enabled: false

Layout/LineLength:
  Max: 80

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Layout/SingleLineBlockChain:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
      - 'spec/**/*.rb'

Lint/ConstantResolution:
  Enabled: false

Lint/Debugger:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Performance/ChainArrayAllocation:
  Exclude:
    - 'spec/**/*.rb'

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/Capybara/SpecificMatcher:
  Enabled: false

RSpec/ContextMethod:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false

RSpec/VariableName:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: always_braces
  Exclude:
    - '**/*gemspec'
    - '**/Gemfile'
    - '**/Steepfile'
    - '**/Rakefile'
    - '**/spec_helper.rb'

Style/ClassVars:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/InlineComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - alias_method
    - gem
    - include
    - puts
    - raise
    - require
    - require_relative
    - ruby
    - source
    - sh

Style/MissingElse:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RedundantPercentQ:
  Exclude:
    - '**/*gemspec'

Style/RedundantReturn:
  Enabled: false

Style/StringHashKeys:
  Exclude:
    - '**/*gemspec'
