require:
  - rubocop-performance

AllCops:
  EnabledByDefault: true
  Exclude:
    - '**/test.rb'
  TargetRubyVersion: 3.0

Bundler/GemComment:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument
  IndentationWidth: 4

Layout/FirstArgumentIndentation:
  IndentationWidth: 4

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/FirstMethodParameterLineBreak:
  Enabled: false

Layout/LineLength:
  Max: 80

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Lint/ConstantResolution:
  Enabled: false

Lint/Debugger:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: always_braces
  Exclude:
    - '**/*gemspec'
    - '**/Gemfile'
    - '**/Steepfile'
    - '**/Rakefile'
    - '**/spec_helper.rb'

Style/Copyright:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/InlineComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - gem
    - puts
    - raise
    - require
    - require_relative
    - ruby
    - source
    - sh

Style/MissingElse:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RedundantPercentQ:
  Exclude:
    - '**/*gemspec'

Style/RedundantReturn:
  Enabled: false

Style/StringHashKeys:
  Exclude:
    - '**/*gemspec'
