class Hash[unchecked out K, unchecked out V] < Object
  def deep_transform_keys!: () { (untyped) -> untyped } -> Hash[K, V]

  def symbolize_keys: () -> Hash[Symbol, V]

  def symbolize_keys!: () -> Hash[Symbol, V]
end
