module JubiSingleton
  def self.included: (untyped base) -> untyped

  module ClassMethods
    def instance: (*untyped) ?{ () -> untyped } -> untyped

    private

    def method_missing: (untyped method, *untyped args) { () -> untyped } -> untyped

    def respond_to_missing?: (untyped method, untyped include_all) -> untyped
  end
end
